baseurl = "/"
theme = "paper"
title = "Nicolas Chaulet"
baseURL = "https://nicolas-chaulet.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
autoSwitchAppearance = false 

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Homepage and blog by Nicolas Chaulet"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  linkedin="nicolas-chaulet-ab293146"
  github="nicolas-chaulet"

  # And you can even create generic menu 
  [[menu.main]]
    identifier = "publications"
    name       = "Publications"
    url        = "/publications/"
  
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"